name: Java CI - JDK 1.8

on:
  push:
    branches:
      - master
      - add-other-starters
      - improvements_vXXXXa
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -P build -B install --file pom.xml
